name = "jkot"
type = "javascript"
compatibility_date = "2022-02-03"
workers_dev = false

[durable_objects]
bindings = [
  { name = "SETTINGS_DO", class_name = "Settings" },
  { name = "ARTICLE_DO", class_name = "Article" },
]

[[migrations]]
tag = "v1"
new_classes = ["Settings", "Article"]