compatibility_date = "2022-02-03"
main = "./dist/worker.ts"
name = "jkot"

[vars]
ORIGIN = "jkot.horrible.workers.dev"

[durable_objects]
bindings = [
  {name = "SETTINGS_DO", class_name = "Settings"},
  {name = "ARTICLE_DO", class_name = "Article"},
]

[[migrations]]
new_classes = ["Settings", "Article"]
tag = "v1"
