compatibility_date = "2022-02-03"
name = "jkot"
type = "javascript"

[build.upload]
format = "modules"
main = "./worker.ts"

[vars]
ORIGIN = "jkot.horrible.workers.dev"

[durable_objects]
bindings = [
  {name = "SETTINGS_DO", class_name = "Settings"},
  {name = "ARTICLE_DO", class_name = "Article"},
]

[[migrations]]
new_classes = ["Settings", "Article"]
tag = "v1"
